### ISSUE TITLE
Need help with nitro 5 AN515-52

### ISSUE THREAD

**Issue by AleX-RNG** [ny4rlk0/BIOS-ACER-NITRO-5-AN515-45#2]
I know it my not be the right place to ask, but anyway. I bricked my laptop when changing ram timings in bios ( I was using original bios, opened advanced settings with a set of commands in keyboard). Tried everything, including Clear CMOS. Crisis Flash seen to not work at all, using bios .fd extracted from Acer website, version 1.28. Can you help me please? Use a CH341A is my only option? 
I have read somewhere there is ways to clear NVRAM and therefore reset bios, but I was unable to find how

**Comment by ny4rlk0** [comment]
If it is opening. Reset BIOS. If it is not openning. Borrow some other RAM check if working. If it is working reset BIOS try older RAM's again if its not working after that buy new RAM. If it is not working reflash BIOS with CH341A. If it is still not working. I would look for a damge in motherboard. Check if BIOS chip is fried. Can you write read from it etc. Does BIOS flasher programs see your chip etc. Otherwise idk.
